name = "cloudflare-docker-proxy"

[observability]
enabled = true

[observability.logs]
enabled = true

[vars]
CUSTOM_DOMAIN = "eastcoal.tech"

[dev]
ip = "0.0.0.0"
port = 443
local_protocol = "https"
