name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[placement]
mode = "smart"


[observability]
enabled = true

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[dev]
ip = "0.0.0.0"
port = 443
local_protocol = "https"

[vars]
CUSTOM_DOMAIN = "eastcoal.tech"
